# Generated by Django 6.0.3 on 2026-03-18 23:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('siren', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'business',
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('siret', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('business', models.ForeignKey(db_column='business_siren', on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='business.business')),
            ],
            options={
                'db_table': 'batiment',
            },
        ),
        migrations.CreateModel(
            name='LegalUnit',
            fields=[
                ('siren', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('statut_diffusion', models.CharField(blank=True, max_length=1, null=True)),
                ('unite_purgee', models.BooleanField(blank=True, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, max_length=1, null=True)),
                ('prenom1', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom2', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom3', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom4', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom_usuel', models.CharField(blank=True, max_length=255, null=True)),
                ('pseudonyme', models.CharField(blank=True, max_length=255, null=True)),
                ('identifiant_association', models.CharField(blank=True, max_length=255, null=True)),
                ('tranche_effectifs', models.CharField(blank=True, max_length=10, null=True)),
                ('annee_effectifs', models.CharField(blank=True, max_length=4, null=True)),
                ('date_dernier_traitement', models.DateTimeField(blank=True, null=True)),
                ('nombre_periodes', models.IntegerField(default=0)),
                ('categorie_entreprise', models.CharField(blank=True, max_length=50, null=True)),
                ('annee_categorie_entreprise', models.CharField(blank=True, max_length=4, null=True)),
                ('activite_principale_naf25', models.CharField(blank=True, max_length=10, null=True)),
                ('business', models.OneToOneField(db_column='business_siren', on_delete=django.db.models.deletion.CASCADE, related_name='legal_unit', to='business.business')),
            ],
            options={
                'db_table': 'legal_unit',
            },
        ),
        migrations.CreateModel(
            name='LegalUnitPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('etat_administratif', models.CharField(blank=True, max_length=1, null=True)),
                ('changement_etat_administratif', models.BooleanField(default=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('changement_nom', models.BooleanField(default=False)),
                ('nom_usage', models.CharField(blank=True, max_length=255, null=True)),
                ('changement_nom_usage', models.BooleanField(default=False)),
                ('denomination', models.CharField(blank=True, max_length=255, null=True)),
                ('changement_denomination', models.BooleanField(default=False)),
                ('denomination_usuelle1', models.CharField(blank=True, max_length=255, null=True)),
                ('denomination_usuelle2', models.CharField(blank=True, max_length=255, null=True)),
                ('denomination_usuelle3', models.CharField(blank=True, max_length=255, null=True)),
                ('changement_denomination_usuelle', models.BooleanField(default=False)),
                ('categorie_juridique', models.CharField(blank=True, max_length=10, null=True)),
                ('changement_categorie_juridique', models.BooleanField(default=False)),
                ('activite_principale', models.CharField(blank=True, max_length=10, null=True)),
                ('nomenclature_activite_principale', models.CharField(blank=True, max_length=20, null=True)),
                ('changement_activite_principale', models.BooleanField(default=False)),
                ('nic_siege', models.CharField(blank=True, max_length=10, null=True)),
                ('changement_nic_siege', models.BooleanField(default=False)),
                ('economie_sociale_solidaire', models.CharField(blank=True, max_length=1, null=True)),
                ('changement_economie_sociale_solidaire', models.BooleanField(default=False)),
                ('societe_mission', models.CharField(blank=True, max_length=1, null=True)),
                ('changement_societe_mission', models.BooleanField(default=False)),
                ('caractere_employeur', models.CharField(blank=True, max_length=1, null=True)),
                ('changement_caractere_employeur', models.BooleanField(default=False)),
                ('legal_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='business.legalunit')),
            ],
            options={
                'db_table': 'legal_unit_period',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddIndex(
            model_name='legalunit',
            index=models.Index(fields=['statut_diffusion'], name='legal_unit_statut__5da23f_idx'),
        ),
        migrations.AddIndex(
            model_name='legalunit',
            index=models.Index(fields=['prenom1', 'prenom_usuel'], name='legal_unit_prenom1_3340e5_idx'),
        ),
        migrations.AddIndex(
            model_name='legalunitperiod',
            index=models.Index(fields=['legal_unit', 'date_debut'], name='legal_unit__legal_u_3a2d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='legalunitperiod',
            index=models.Index(fields=['date_debut', 'date_fin'], name='legal_unit__date_de_999ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='legalunitperiod',
            index=models.Index(fields=['nom', 'denomination'], name='legal_unit__nom_26f4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='legalunitperiod',
            index=models.Index(fields=['activite_principale'], name='legal_unit__activit_937fd9_idx'),
        ),
    ]
