# Generated by Django 6.0.3 on 2026-03-18 20:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseLocation',
            fields=[
                ('siret', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('enterprise', models.ForeignKey(db_column='enterprise_siren', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='enterprises.enterprise')),
            ],
            options={
                'db_table': 'enterprise_locations',
            },
        ),
        migrations.DeleteModel(
            name='Batiment',
        ),
    ]
